spring:
  application:
    name: Spring Cars Demo

  profiles:
    active: store1
  datasource:
    url: "jdbc:mysql://localhost:3306/hw_Spring?createDatabaseIfNotExist=true"
    username: "root"
    password: "Maksym674"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      uri: "mongodb+srv://user:user@cluster0.7olkati.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      database: "car_maintenance"
#  liquibase:
#    enabled: true
#    drop-first: false
#    change-log: classpath:/db/changelog/db.changelog-master.yaml  # Correct path with extension
#    default-schema: public
#logging:
#  level:
#    liquibase: DEBUG
